--return {
--    name = "PrismaticHelper/SpeedBerry",
--    depth = -100,
--    placements = {
--        name = "berry",
--        data = {
--            time = 60
--        }
--    },
--    texture = "collectables/strawberry/idle00"
--}
return nil